sample_per_cluster: 10
cluster_num: 200
train_init_model: true
task: CTA
dataset: WebTable
embedding_model_path: /data/home/wangys/sentence_transformer_model/bge-large-en-1.5
train_file_path: /data/home/wangys/MELD/dataset/CTA/webtable_train_few.json
eval_file_path: train/CTA/WebTable/train-init.json
devices: 0,1,2,3,4,5,6,7
batch_size: 4
## LLM config
model_name_or_path: /data/home/wangys/model/Qwen2.5-0.5B-Instruct
stage: sft
template: qwen
adapter_name_or_path: lora/qwen-0.5B/CTA/WebTable/init
require_grad: true
require_ppl: true