model_name_or_path: /data/yanmengyi/huggingface/Mistral-7B-Instruct-v0.2
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
template: mistral
cutoff_len: 1024
dataset_dir: /data/yanmengyi/LLaMA-Factory/data
dataset: __DATASET__
output_dir: __OUT__
num_train_epochs: 1.0
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 0.0001
lr_scheduler_type: cosine
warmup_ratio: 0.05
logging_steps: 20
save_strategy: "no"
fp16: true
bf16: false
overwrite_output_dir: true
overwrite_cache: true
report_to: none
preprocessing_num_workers: 8
seed: 0
