bf16: true
cutoff_len: 1024
dataset: Abt-Buy-Match-P1
ddp_timeout: 180000000
deepspeed: src/ds_z0_config.json
do_train: true
enable_liger_kernel: true
finetuning_type: lora
learning_rate: 0.0001
logging_steps: 10
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: /data/home/wangys/model/qwen-2.5-7B
neat_packing: true
num_train_epochs: 5.0
output_dir: lora/qwen2.5-7B/RE/RE/w-IF
overwrite_cache: false
overwrite_output_dir: true
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 500
stage: sft
template: qwen
train_file_path: train/RE/RE/train-select-w-IF.json
warmup_ratio: 0.1
