sample_per_cluster: 15
cluster_num: 100
train_init_model: true
task: DC
dataset: hospital
embedding_model_path: /data/home/wangys/sentence_transformer_model/bge-large-en-1.5
train_file_path: train/DC/hospital/hospital-train.json
eval_file_path: train/DC/hospital/train-init.json
test_file_path: train/DC/hospital/hospital-test.json
devices: 0,1,2,3,4,5,6,7
batch_size: 8
## LLM config
model_name_or_path: /data/home/wangys/model/Qwen2.5-0.5B-Instruct
stage: sft
template: qwen
adapter_name_or_path: lora/qwen-0.5B/DC/hospital/init
require_grad: true
require_ppl: true
require_inference: true
cutoff_len: 2048
guided_choices: false