bf16: true
cutoff_len: 2048
dataset: Abt-Buy-Match-P1
train_file_path: train/CTA/WebTable/train-select.json
ddp_timeout: 180000000
deepspeed: /data/home/wangys/LLAMA-backup/LLaMA-Factory/examples/deepspeed/ds_z0_config.json
do_train: true
finetuning_type: lora
learning_rate: 0.0001
logging_steps: 10
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: /data/home/wangys/model/Mistral-7B-Instruct-v0.2
num_train_epochs: 5.0
output_dir: lora/mistral-7B/CTA/WebTable/select
overwrite_cache: false
overwrite_output_dir: true
plot_loss: true
preprocessing_num_workers: 16
save_steps: 500
stage: sft
template: mistral
warmup_ratio: 0.1
enable_liger_kernel: true
neat_packing: true
report_to: none