bf16: true
cutoff_len: 1024
dataset: Abt-Buy-Match-P1
train_file_path: /data/home/wangys/MELD/dataset/CTA/SimTab_Train_few.json
ddp_timeout: 180000000
deepspeed: /data/home/wangys/LLAMA-backup/LLaMA-Factory/examples/deepspeed/ds_z0_config.json
do_train: true
finetuning_type: lora
learning_rate: 0.0001
logging_steps: 10
lora_rank: 16
lora_target: q_proj
lr_scheduler_type: cosine
model_name_or_path: /data/home/wangys/model/Qwen2.5-0.5B-Instruct
num_train_epochs: 3.0
output_dir: lora/qwen-0.5B/CTA/SimTab/init
overwrite_cache: false
overwrite_output_dir: true
plot_loss: true
preprocessing_num_workers: 16
save_steps: 500
stage: sft
template: qwen
warmup_ratio: 0.1
enable_liger_kernel: true
neat_packing: true
report_to: none