bf16: true
cutoff_len: 2048
dataset: Abt-Buy-Match-P1
ddp_timeout: 180000000
deepspeed: /data/home/wangys/LLAMA-backup/LLaMA-Factory/examples/deepspeed/ds_z0_config.json
do_train: true
enable_liger_kernel: true
finetuning_type: lora
learning_rate: 0.0001
logging_steps: 10
lora_rank: 16
lora_target: q_proj
lr_scheduler_type: cosine
model_name_or_path: /data/home/wangys/model/Qwen2.5-0.5B-Instruct
neat_packing: true
num_train_epochs: 3.0
output_dir: lora/qwen-0.5B/ER/semi-text-c/init
overwrite_cache: false
overwrite_output_dir: true
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 500
stage: sft
template: qwen
train_file_path: train/ER/semi-text-c/semi-text-c-train.json
warmup_ratio: 0.1
